name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Set Google Cloud service account key
        run: echo "${{ secrets.SERVICE_ACCOUNT }}" > key.json
        # Note: Replace secrets.GOOGLE_CLOUD_KEY_JSON with your actual secret name in GitHub Secrets

      - name: Configure Google Cloud credentials
        run: gcloud auth activate-service-account --key-file=key.json
        # Note: If gcloud CLI is not available, make sure to install it before this step

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Cleanup
        run: rm key.json
